Allow unwrap custom active_job.queue_adapter
ixti/sidekiq-throttled-clone pull request #2
Opened 2022-06-13 04:58 UTC by longkt90

Small improvement from https://github.com/sensortower/sidekiq-throttled/pull/116 to allow unwrap of custom job adapters

2022-06-13 21:50 UTC, ixti requested changes
Thank you for your contribution. I believe we should try `"class"` before `"wrapped"`, though. :D

2022-06-13 21:50 UTC, ixti commented on lib/sidekiq/throttled.rb
> +        jid = message.fetch("jid", false)
Let's try `"class"` first, then `"wrapped"`. Also, original logic was short-circuiting and returning `false` if no `"class"` found, which now I see was a bit defective.

```suggestion
        job = message.fetch("class") { message.fetch("wrapped", false) }
        return unless job

        jid = message.fetch("jid", false)
        return unless jid
```

2022-06-13 21:55 UTC, ixti commented on lib/sidekiq/throttled.rb
> +        jid = message.fetch("jid", false)
With the proposed changes above, you won't need to remove rubocop disable :rofl:

2022-06-14 10:17 UTC, longkt90 commented on lib/sidekiq/throttled.rb
> +        jid = message.fetch("jid", false)
afraid you need to do wrapped first, since class will be always "JobWrapper" for rails https://github.com/rails/rails/blob/18707ab17fa492eb25ad2e8f9818a320dc20b823/activejob/lib/active_job/queue_adapters/sidekiq_adapter.rb#L23

2022-06-14 10:39 UTC, longkt90 commented on lib/sidekiq/throttled.rb
> +        jid = message.fetch("jid", false)
I fixed the other point of early returning

2022-06-14 12:54 UTC, ixti commented on lib/sidekiq/throttled.rb
> +        jid = message.fetch("jid", false)
> afraid you need to do wrapped first, since class will be always "JobWrapper" for rails 

Oh. Indeed. Totally overlooked that.

2022-06-14 12:56 UTC, ixti approved these changes

2022-06-14 12:57 UTC, merged

2022-06-14 12:57 UTC, ixti commented
Thank you. Will release asap.

2022-06-14 15:52 UTC, ixti commented
Released as 0.16.1